### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by jlandmann** [OGGM/world-glacier-explorer#15]
In my precious PhD Thesis (:-P) I would like to cite the world glaciers explorer, since the app I have built for CRAMPON heavily relies on the content of this repository. As far as my search skills go, I couldn't find an info on what the preferred citation is though.

Shall I cite it as OGGM itself, as OGGM-Edu (I couldn't find to how to cite that either) or rather hand-knit a "misc" bibtex entry?

**Comment by fmaussion** [comment]
thanks! yes I think it's fine to just cite it as a website. We could offer Zenodo DOIs but that would be for the code only, so mybe not very interesting.

**Comment by jlandmann** [comment]
Okay, perfect, thanks for your answer! :-)
